# ------------------------------------------------------------
# Nome da aplicação Spring
# Usado principalmente para logs, monitoramento e identificação
# em ambientes com múltiplos serviços.
# ------------------------------------------------------------
spring.application.name=stock


# ------------------------------------------------------------
# Perfil ativo da aplicação
#
# ${SPRING_PROFILES_ACTIVE:local}
# Significa:
# - Se existir variável de ambiente SPRING_PROFILES_ACTIVE,
#   ela será usada.
# - Caso contrário, o valor padrão será "local".
#
# Isso permite alternar entre:
# local, dev, prod, test, etc.
# ------------------------------------------------------------
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}


# ------------------------------------------------------------
# Porta onde o servidor Spring Boot irá rodar
#
# ${PORT:8080}
# - Se existir variável de ambiente PORT, usa ela.
# - Caso contrário, roda na porta 8080.
#
# Muito usado em deploy (ex: Heroku, Railway, Render, etc).
# ------------------------------------------------------------
server.port=${PORT:8080}


# ------------------------------------------------------------
# Estratégia de criação/atualização das tabelas pelo Hibernate
#
# update:
# - Cria tabelas se não existirem
# - Atualiza estrutura sem apagar dados
#
# Outras opções:
# create      ? apaga e recria tudo
# create-drop ? recria e apaga ao finalizar
# validate    ? apenas valida estrutura
# none        ? não faz nada
#
# ------------------------------------------------------------
spring.jpa.hibernate.ddl-auto=update


# ------------------------------------------------------------
# Exibe no console os SQL gerados pelo Hibernate
#
# Útil para debug e aprendizado.
# Em produção normalmente deve ficar false.
# ------------------------------------------------------------
spring.jpa.show-sql=true


# ------------------------------------------------------------
# Formata o SQL exibido no console
#
# Deixa a query mais legível:
# SELECT
#     p.id,
#     p.name
# FROM product p
# ------------------------------------------------------------
spring.jpa.properties.hibernate.format_sql=true