# ------------------------------------------------------------
# URL dinâmica de conexão com PostgreSQL usando
# variáveis de ambiente.
#
# Estrutura:
# jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
#
# ${PGHOST}     ? endereço do servidor do banco
# ${PGPORT}     ? porta do banco
# ${PGDATABASE} ? nome do banco
#
# Essas variáveis são fornecidas pelo ambiente
# (ex: Render, Railway, Docker, etc).
#
# Exemplo resolvido em produção:
# jdbc:postgresql://dpg-xxxxx.render.com:5432/stock_db
# ------------------------------------------------------------
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}


# ------------------------------------------------------------
# Usuário do banco vindo de variável de ambiente
#
# ${PGUSER} será substituído automaticamente
# pelo valor definido no servidor.
# ------------------------------------------------------------
spring.datasource.username=${PGUSER}


# ------------------------------------------------------------
# Senha do banco vindo de variável de ambiente
#
# Muito mais seguro do que deixar fixo no código.
# ------------------------------------------------------------
spring.datasource.password=${PGPASSWORD}


# ------------------------------------------------------------
# Driver JDBC do PostgreSQL
#
# Em versões recentes do Spring Boot,
# essa linha pode ser opcional.
# ------------------------------------------------------------
spring.datasource.driver-class-name=org.postgresql.Driver